language: R
r_packages:
  - covr
after_success:
  - Rscript -e 'covr::codecov()'
cache: packages
os:
  - linux
  - osx
before_install:
  - if ["$TRAVIS_OS_NAME" = "linux"]; then sudo apt-get -y install libv8-dev; fi
