# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sim_ideal_cpp <- function(init_pop_size, vaccinations, cases_novac, ve, lag, deterministic) {
    .Call(`_impactflu_sim_ideal_cpp`, init_pop_size, vaccinations, cases_novac, ve, lag, deterministic)
}

